lab7/myimgur/accounts/urls.py
from django.urls import path

from . import views

app_name = 'accounts'
urlpatterns = [
    path('sign-up', views.SignUpView.as_view(), name='signup'),
]

lab7/myimgur/app/urls.py
from django.urls import path

from . import views

app_name = 'app'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:image_id>/', views.detail, name='detail'),
    path('<int:image_id>/comment', views.comment, name='comment'),
    path('<int:image_id>/upvote', views.upvote, name="upvote"),
    path('<int:image_id>/downvote', views.downvote, name="downvote"),
    path('new', views.create_image, name="create_image"),
    path('<int:image_id>/edit', views.update_image, name="edit_image"),
    path('<int:image_id>/delete', views.delete_image, name="delete_image"),
  
]

lab7/myimgur/imgur/urls.py
from django.contrib import admin
from django.urls import include,path
from app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('images/', include('app.urls')),
    path('', views.index, name='index'), 
]

lab7/myimgur/accounts/models.py
from django.db import models

# Create your models here.

lab7/myimgur/app/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User


# Create your models here.
class TimeStamped(models.Model):
    created_at = models.DateTimeField(editable=False)
    updated_at = models.DateTimeField(editable=False)

    def save(self, *args, **kwargs):
        if not self.created_at:
            self.created_at = timezone.now()

        self.updated_at = timezone.now()
        return super(TimeStamped, self).save(*args, **kwargs)

    class Meta:
        abstract = True


class Image(TimeStamped):
    title = models.CharField(max_length=128, unique=True, blank=False)
    url = models.CharField(max_length=512)
    description = models.TextField(blank=True)
    pub_date = models.DateTimeField('Published at')
    upvotes = models.IntegerField(default=0)
    downvotes = models.IntegerField(default=0)

    def __str__(self):
        return self.title

    def comments_count(self):
        return Image.comment_set.count()

    def votes(self):
        return self.upvotes - self.downvotes

    def vote_score(self):
        upvotes=self.vote_set.filter(upvote=True).count()
        downvotes=self.vote_set.filter(upvote=False).count()
        return upvotes - downvotes
    
    def vote_by(self,user):
        if user.is_authenticated:
            return Vote.objects.filter(user=user,image=self).first()
        else:
            return None

class Comment(TimeStamped):
    image = models.ForeignKey(Image, on_delete=models.CASCADE)
    text = models.TextField(blank=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.text[:80]

    def author(self):
        return self.user.username    

class Vote(TimeStamped):
    image = models.ForeignKey(Image, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    upvote = models.BooleanField(null=False, default=True)
    
    class Meta:
        constraints = [models.UniqueConstraint(name='user_vote', fields=['image','user'])]

    def __str__(self):
        return f"{self.user.username} voted on {self.image.title}"
        
    def downvote(self):
        return not self.upvote

lab7/myimgur/app/forms.py
from django.db.models.base import Model
from .models import Image, Comment
from django.forms import ModelForm
from bootstrap_datepicker_plus.widgets import DateTimePickerInput

class ImageForm(ModelForm):
    class Meta:
        model = Image
        fields=['title','url','description','pub_date']
        widgets = {
            'pub_date': DateTimePickerInput(),
        }

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['text']

lab7/myimgur/accounts/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.urls import reverse_lazy
from django.views import generic

class SignUpView(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('login')
    template_name = 'registration/signup.html'

lab7/myimgur/app/views.py
from django.shortcuts import render, get_object_or_404
from django.http import JsonResponse, HttpResponseRedirect
from django.urls import reverse
from .models import Image, Comment, Vote
from .forms import CommentForm, ImageForm
# Create your views here.

def index(request):
    images = Image.objects.order_by('-pub_date')
    votes = [image.vote_by(request.user) for image in images]
    context = { 'images_with_votes': zip(images, votes)}
    return render(request, 'app/index.html', context)

def detail(request, image_id):
    image = get_object_or_404(Image,pk=image_id)
    context = {'image': image, 
               'vote' : image.vote_by(request.user),
               'comments': image.comment_set.all(),
               'form' : CommentForm(),
              }
    return render(request, 'app/detail.html', context)

def create_image(request):
    if request.method == 'POST' and request.user.is_authenticated:
        form = ImageForm(request.POST)
        if form.is_valid():
            saved_image = form.save()
            return HttpResponseRedirect(reverse('app:detail',args=(saved_image.id,)))
    else:
        form = ImageForm()
    context = {'form' : form, 'action' : 'create'}
    return render(request, 'app/create_image.html', context)

def update_image(request, image_id):
    image = get_object_or_404(Image,pk=image_id)
    if request.method == 'POST' and request.user.is_authenticated:
        form = ImageForm(request.POST, instance=image)
        if form.is_valid():
            saved_image = form.save()
            return HttpResponseRedirect(reverse('app:detail',args=(saved_image.id,)))
    else:
        form = ImageForm(instance=image)
    context = {'form' : form, 'action' : 'update'}
    return render(request, 'app/create_image.html', context)

def delete_image(request, image_id):
    image = get_object_or_404(Image,pk=image_id)
    if request.method == 'POST' and request.user.is_authenticated:
        image.delete()
    return HttpResponseRedirect(reverse('app:index'))



def comment(request, image_id):
    if request.method == 'POST':
        image = get_object_or_404(Image, pk=image_id)
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.image = image
            comment.user = request.user
            comment.save()
            return HttpResponseRedirect(reverse('app:detail',args=(comment.image.id,)))
        else:
            return render(request,'app/detail.html', {
                'image' : image,
                'comments' : image.comment_set.all(),
                'form' : form,
            })
    else:
        return HttpResponseRedirect(reverse('app:detail', args=(image_id,)))      


def vote(request,image_id,upvote):
    image = get_object_or_404(Image, pk=image_id)
    vote = Vote.objects.filter(user=request.user, image=image).first()
    if vote:
        if vote.upvote == upvote:
            vote.delete()
            return None
        else:
            vote.upvote = upvote
    else:
        vote = Vote(user=request.user, image=image, upvote=upvote)
    try:
        vote.full_clean()
        vote.save()
    except:
        return None
    else:
        return vote
    
 


def upvote(request,image_id):
    if request.method == 'POST' and request.user.is_authenticated:
        vote(request,image_id,True)
    return HttpResponseRedirect(reverse('app:detail', args=(image_id,)))
    


def downvote(request,image_id):
    if request.method == 'POST' and request.user.is_authenticated:
        vote(request,image_id,False)
    return HttpResponseRedirect(reverse('app:detail', args=(image_id,)))

lab7/myimgur/app/templates/app/base.html
{% load static %}
<html>
  <head>
    <title>My Lame Imgur</title>

    <link
      href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
      crossorigin="anonymous"
      integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm"
      rel="stylesheet"
    />
    <script
      src="https://code.jquery.com/jquery-3.2.1.min.js"
      crossorigin="anonymous"
      integrity="sha384-xBuQ/xzmlsLoJpyjoggmTEz8OWUFM0/RC5BsqQBDX2v5cMvDHcMakNTNrHIW2I5f"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
      crossorigin="anonymous"
      integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
    ></script>
    <script
      src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
      crossorigin="anonymous"
      integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
    ></script>

    {% block extrahead %} {% endblock %}

    <link rel="stylesheet" href="{% static 'app/css/app.css' %}" />
  </head>
  <body>
    <div class="page-header">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <a class="navbar-brand" href="/">My Lame Imgur</a>
        <button
          class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="/"
                >Home <span class="sr-only">(current)</span></a
              >
            </li>
          </ul>
          <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link" href="#">Hi {{ user.username }}!</a>
            </li>
            {% if user.is_superuser %}
            <li class="nav-item">
              <a class="nav-link" href="/admin">Admin Dashboard</a>
            </li>
            {% endif %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'logout' %}">LogOut</a>
            </li>
            {% else %}
            <li class="nav-item">
              <a class="nav-link" href="{% url 'login' %}">LogIn</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'accounts:signup' %}">SignUp</a>
            </li>
            {% endif %}
          </ul>
        </div>
      </nav>
    </div>
    <div class="content container">
      <div class="row">
        <div class="col-md-12">
          <div class="jumbotron fluid-jumbotron">
            <div class="container">
              <h1 class="display-4">My Lame Imgur</h1>
              <p class="lead">
                Your one stop place for posting your lamest images!
              </p>
            </div>
          </div>
        </div>
      </div>
      <div class="row">
        <div class="col-md-12">{% block content %} {% endblock %}</div>
      </div>
    </div>
  </body>
</html>

lab7/myimgur/app/templates/app/create_image.html
{% extends 'app/base.html' %} {% block content %} {% block extrahead %}
{{form.media}} {% endblock extrahead %}
<div class="container">
  {% if action == "create" %}
  <h2>Submit new image</h2>
  {% elif action == "update" %}
  <h2>Edit image</h2>
  {% endif %}

  <div class="row">
    <form method="post" novalidate>
      {% csrf_token %} {% include 'includes/bs4_form.html' with form=form %}
      <button type="submit" class="btn btn-primary">Submit</button>
    </form>
  </div>
</div>
{% endblock %}

lab7/myimgur/app/templates/app/detail.html
{% extends 'app/base.html' %} {% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-6">
      <div class="date">{{ image.pub_date }}</div>

      <div>
        {% include "includes/vote_buttons.html" with image=image vote=vote %}
      </div>

      <h2>{{ image.title }}</h2>
      <img class="app-fit" src="{{image.url}}" alt="" />
    </div>
    <div class="col-md-6">
      <h3>Description</h3>
      <p>{{ image.description|linebreaksbr }}</p>
      <h3>Comments</h3>
      {% for comment in comments %}
      <div class="border comment">
        <p class="red">Author: {{ comment.author }} ({{comment.created_at}})</p>
        <p class="secondary">{{ comment.text }}</p>
      </div>
      {% endfor %} {% if user.is_authenticated %}
      <h2>Post a comment</h2>
      {% if error_message %}
      <p><strong>{{ error_message }}</strong></p>
      {% endif %}

      <form
        action="{% url 'app:comment' image.id %}"
        method="post"
        class="border"
      >
        {% csrf_token %} {% include "includes/bs4_form.html" with form=form %}
        <button type="submit" class="btn btn-primary">Post Comment</button>
      </form>
      {% endif %}
    </div>
  </div>
</div>
{% endblock %}

lab7/myimgur/app/templates/app/index.html
{% extends 'app/base.html' %} {% block content %}
<div class="row">
  <div class="col-md10">
    <p><a href="{% url 'app:create_image' %}">Submit new image</a></p>
  </div>
</div>
{% for image, vote in images_with_votes %}
<div class="row">
  <div class="col-md-2">
    <img class="app-fit" src="{{image.url}}" alt="" />
  </div>
  <div class="col-md-10">
    <div class="date">
      <p class="red">
        Published: {{ image.pub_date }}; Comments: {{ image.comment_set.count }}
        <a href="{% url 'app:edit_image' image.id %}">Edit</a> |
        <a href="#" id="delete_{{image.id}}">Delete</a>
        <form action="{% url 'app:delete_image' image.id %}" 
              method="post" 
              id="delete_form_{{ image.id }}" 
              class="hidden">
          {% csrf_token %}
        </form>
      <script>
        $(document).on('click', '#delete_{{image.id}}',function(){
          $('#delete_form_{{image.id}}').submit();
        });
      </script>
      </p>
    </div>
    {% include "includes/vote_buttons.html" with image=image vote=vote %}
    <h2><a href="{% url 'app:detail' image.id %}">{{ image.title }}</a></h2>
    <p>{{ image.description|linebreaksbr }}</p>
  </div>
</div>
{% endfor %} {% endblock %}

lab7/myimgur/app/templates/includes/bs4_form.html
{% load widget_tweaks %} 
{% for hidden_field in form.hidden_fields %}
    {{ hidden_field }}
  {% endfor %}

  {% if form.non_field_errors %}
    <div class="alert alert-danger" role="alert">
      {% for error in form.non_field_errors %}
        {{ error }}
      {% endfor %}
    </div>
  {% endif %}

  {% for field in form.visible_fields %}
    <div class="form-group">
      {{ field.label_tag }}

      {% if form.is_bound %}
        {% if field.errors %}
          {% render_field field class="form-control is-invalid" %}
          {% for error in field.errors %}
            <div class="invalid-feedback">
              {{ error }}
            </div>
          {% endfor %}
        {% else %}
          {% render_field field class="form-control is-valid" %}
        {% endif %}
      {% else %}
        {% render_field field class="form-control" %}
      {% endif %}

      {% if field.help_text %}
        <small class="form-text text-muted">{{ field.help_text }}</small>
      {% endif %}
    </div>
  {% endfor %}

lab7/myimgur/app/templates/includes/delete_image_link.html
<a href="#" id="delete_{{image.id}}">Delete</a>
<form
  action="{% url 'app:delete_image' image.id %}"
  method="post"
  id="delete_form_{{ image.id }}"
  class="hidden"
>
  {% csrf_token %}
</form>
<script>
  $(document).on("click", "#delete_{{image.id}}", function () {
    $("#delete_form_{{image.id}}").submit();
  });
</script>

lab7/myimgur/app/templates/includes/vote_buttons.html
<form
  action="{% url 'app:upvote' image.id %}"
  method="post"
  role="form"
  class="form-inline float-left"
>
  {% csrf_token %}
  <input
    type="submit"
    value="+"
    class="btn {{ vote.upvote|yesno:'btn-success,' }}"
  />
</form>

<span class="vote-score float-left">{{ image.vote_score }}</span>

<form
  action="{% url 'app:downvote' image.id %}"
  method="post"
  role="form"
  class="form-inline float-left"
>
  {% csrf_token %}
  <input
    type="submit"
    value="-"
    class="btn {{ vote.downvote|yesno:'btn-danger,' }}"
  />
</form>